version: 0.0
os: linux

files:
  - source: /target/ROOT.war
    destination: /tmp/staging/
  - source: /scripts/configure_http_port.xsl
    destination: /tmp/staging/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/basic_health_check