#!/bin/bash

set -e

CATALINA_HOME='/usr/share/tomcat8'
DEPLOY_TO_ROOT='true'
#CONTEXT_PATH='##CONTEXT_PATH##'

TEMP_STAGING_DIR='/tmp/staging'
WAR_STAGED_LOCATION="$TEMP_STAGING_DIR/ROOT.war"

# In Tomcat, ROOT.war maps to the server root
if [[ "$DEPLOY_TO_ROOT" = 'true' ]]; then
    CONTEXT_PATH='ROOT'
fi

# remove everything in the webapps directory
rm -rf $CATALINA_HOME/webapps/*

# Copy the WAR file to the webapps directory
cp $WAR_STAGED_LOCATION $CATALINA_HOME/webapps/$CONTEXT_PATH.war

service tomcat8 start